/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme/custom-theme.ts
 * Command: astryx theme build theme/custom-theme.ts --out theme/custom-theme.css
 * CLI: @astryxdesign/cli@0.5.2
 * Core: @astryxdesign/core@0.5.2
 */

/// <reference path="./insta-reply.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const instaReplyTheme: DefinedTheme;
