/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme/custom-theme.ts
 * Command: astryx theme build theme/custom-theme.ts --out theme/custom-theme.css
 * CLI: @astryxdesign/cli@0.5.2
 * Core: @astryxdesign/core@0.5.2
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
